version: 2
root-markers:
  - .git/
log-file: /tmp/efm-log
log-level: 1
lint-debounce: 1s
tools:
  eslint: &eslint
    lint-command: 'yarn run eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
languages:
  typescript:
    - <<: *eslint

  typescriptreact:
    - <<: *eslint

  tsx:
    - <<: *eslint
