[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
format = false
nodePath = ""
onIgnoredFiles = "off"
packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { enable = false, mode = "all" }
experimental = { useFlatConfig = false }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "location" }

[language-server.typescript-language-server.config]
documentFormatting = false

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = 'prettierd', args = ["file.ts"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = 'prettierd', args = ["file.tsx"] }
auto-format = true
